package vip.xjdai.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2019-09-10T15:27:38.227+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebserviceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebserviceHttpPost {

    /**
     * 获取本机注册码序号
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getRegCode();

    /**
     * 8.1 价格公示
     */
    @WebMethod(operationName = "QueryPriceBoardInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String queryPriceBoardInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 7.1 住院日清单、出院清单
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String inhosBill(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 获取服务器时间
     */
    @WebMethod(operationName = "Getsysdate")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getsysdate();

    /**
     * 3.1 排班信息
     */
    @WebMethod(operationName = "GetSchemaInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getSchemaInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 10.2 门诊用药记录
     */
    @WebMethod(operationName = "GetOrderInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getOrderInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 5.4 根据发票号或者收据号获取收费明细
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getFeeDetailByfinanceNo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 9.1 检验主表
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getLisResultInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.4 通过身份证查询患者当前在院的住院编号
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getInpatientNo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 3.3 挂号、预约转挂号
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String insertRegisterInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 1.1 身份证关联的所有档案
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getExistProfile(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.2 医生信息
     */
    @WebMethod(operationName = "DocInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String docInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 6.2 住院押金费充值确认
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String hospitalizationExpensesRecharge(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 6.1 住院费余额查询
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getHospitalizationExpenses(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 7.2 住院日清单、出院清单
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String inhosBillnew(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 9.3 获取检查报告单
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getPacsResultInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 3.2.1 查询预约状态
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getBookingState(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 10.1 查询历次门诊就诊记录
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getClinicRecordsInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.1获取医生排班
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String querySchedule(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.1 科室信息
     */
    @WebMethod(operationName = "DeptInfo")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String deptInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 5.2 获取处方信息
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getPrescriptionInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 1.2 建立门诊档案
     */
    @WebMethod(operationName = "CreateProfile")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String createProfile(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 3.2 预约挂号、预约取消
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String insertBooking(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 4.2患者排队查询
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getQueueForPatient(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 5.1 获取有未缴费处方的门诊记录
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getUnpaidClinicInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.3 通过实物就诊卡查询患者在医院的门诊患者编号
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getPatientNO(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 5.3 门诊结算确认
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String saveFee(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 3.4 查询挂号状态
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getClinicState(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 4.1科室排队查询
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getQueueForDept(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 9.2 检验明细
     */
    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String getLisResultDetilInfo(
        @WebParam(partName = "strInput", name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );
}
