spring:
  activemq:
    broker-url: tcp://192.168.117.141:61616
    user: admin
    password: 123456
    in-memory: false      #true 表示使用内置的MQ，false则连接服务器
    pool:
      enabled: true       #true表示使用连接池；false时，每发送一条数据创建一个连接
      max-connections: 10 #连接池最大连接数
      idle-timeout: 30000 #空闲的连接过期时间，默认为30秒
  jms:
    pub-sub-domain: true  #如果为True，则是Topic；如果是false或者默认则是queue。


