
package vip.xjdai.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2019-09-10T15:27:38.220+08:00
 * Generated source version: 3.1.17
 * 
 */
public final class WebserviceHttpGet_WebserviceHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Webservice");

    private WebserviceHttpGet_WebserviceHttpGet_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Webservice.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Webservice ss = new Webservice(wsdlURL, SERVICE_NAME);
        WebserviceHttpGet port = ss.getWebserviceHttpGet();  
        
        {
        System.out.println("Invoking getRegCode...");
        java.lang.String _getRegCode__return = port.getRegCode();
        System.out.println("getRegCode.result=" + _getRegCode__return);


        }
        {
        System.out.println("Invoking queryPriceBoardInfo...");
        java.lang.String _queryPriceBoardInfo_strInput = "";
        java.lang.String _queryPriceBoardInfo__return = port.queryPriceBoardInfo(_queryPriceBoardInfo_strInput);
        System.out.println("queryPriceBoardInfo.result=" + _queryPriceBoardInfo__return);


        }
        {
        System.out.println("Invoking inhosBill...");
        java.lang.String _inhosBill_strInput = "";
        java.lang.String _inhosBill__return = port.inhosBill(_inhosBill_strInput);
        System.out.println("inhosBill.result=" + _inhosBill__return);


        }
        {
        System.out.println("Invoking getsysdate...");
        java.lang.String _getsysdate__return = port.getsysdate();
        System.out.println("getsysdate.result=" + _getsysdate__return);


        }
        {
        System.out.println("Invoking getSchemaInfo...");
        java.lang.String _getSchemaInfo_strInput = "";
        java.lang.String _getSchemaInfo__return = port.getSchemaInfo(_getSchemaInfo_strInput);
        System.out.println("getSchemaInfo.result=" + _getSchemaInfo__return);


        }
        {
        System.out.println("Invoking getOrderInfo...");
        java.lang.String _getOrderInfo_strInput = "";
        java.lang.String _getOrderInfo__return = port.getOrderInfo(_getOrderInfo_strInput);
        System.out.println("getOrderInfo.result=" + _getOrderInfo__return);


        }
        {
        System.out.println("Invoking getFeeDetailByfinanceNo...");
        java.lang.String _getFeeDetailByfinanceNo_strInput = "";
        java.lang.String _getFeeDetailByfinanceNo__return = port.getFeeDetailByfinanceNo(_getFeeDetailByfinanceNo_strInput);
        System.out.println("getFeeDetailByfinanceNo.result=" + _getFeeDetailByfinanceNo__return);


        }
        {
        System.out.println("Invoking getLisResultInfo...");
        java.lang.String _getLisResultInfo_strInput = "";
        java.lang.String _getLisResultInfo__return = port.getLisResultInfo(_getLisResultInfo_strInput);
        System.out.println("getLisResultInfo.result=" + _getLisResultInfo__return);


        }
        {
        System.out.println("Invoking getInpatientNo...");
        java.lang.String _getInpatientNo_strInput = "";
        java.lang.String _getInpatientNo__return = port.getInpatientNo(_getInpatientNo_strInput);
        System.out.println("getInpatientNo.result=" + _getInpatientNo__return);


        }
        {
        System.out.println("Invoking insertRegisterInfo...");
        java.lang.String _insertRegisterInfo_strInput = "";
        java.lang.String _insertRegisterInfo__return = port.insertRegisterInfo(_insertRegisterInfo_strInput);
        System.out.println("insertRegisterInfo.result=" + _insertRegisterInfo__return);


        }
        {
        System.out.println("Invoking getExistProfile...");
        java.lang.String _getExistProfile_strInput = "";
        java.lang.String _getExistProfile__return = port.getExistProfile(_getExistProfile_strInput);
        System.out.println("getExistProfile.result=" + _getExistProfile__return);


        }
        {
        System.out.println("Invoking docInfo...");
        java.lang.String _docInfo_strInput = "";
        java.lang.String _docInfo__return = port.docInfo(_docInfo_strInput);
        System.out.println("docInfo.result=" + _docInfo__return);


        }
        {
        System.out.println("Invoking hospitalizationExpensesRecharge...");
        java.lang.String _hospitalizationExpensesRecharge_strInput = "";
        java.lang.String _hospitalizationExpensesRecharge__return = port.hospitalizationExpensesRecharge(_hospitalizationExpensesRecharge_strInput);
        System.out.println("hospitalizationExpensesRecharge.result=" + _hospitalizationExpensesRecharge__return);


        }
        {
        System.out.println("Invoking getHospitalizationExpenses...");
        java.lang.String _getHospitalizationExpenses_strInput = "";
        java.lang.String _getHospitalizationExpenses__return = port.getHospitalizationExpenses(_getHospitalizationExpenses_strInput);
        System.out.println("getHospitalizationExpenses.result=" + _getHospitalizationExpenses__return);


        }
        {
        System.out.println("Invoking inhosBillnew...");
        java.lang.String _inhosBillnew_strInput = "";
        java.lang.String _inhosBillnew__return = port.inhosBillnew(_inhosBillnew_strInput);
        System.out.println("inhosBillnew.result=" + _inhosBillnew__return);


        }
        {
        System.out.println("Invoking getPacsResultInfo...");
        java.lang.String _getPacsResultInfo_strInput = "";
        java.lang.String _getPacsResultInfo__return = port.getPacsResultInfo(_getPacsResultInfo_strInput);
        System.out.println("getPacsResultInfo.result=" + _getPacsResultInfo__return);


        }
        {
        System.out.println("Invoking getBookingState...");
        java.lang.String _getBookingState_strInput = "";
        java.lang.String _getBookingState__return = port.getBookingState(_getBookingState_strInput);
        System.out.println("getBookingState.result=" + _getBookingState__return);


        }
        {
        System.out.println("Invoking getClinicRecordsInfo...");
        java.lang.String _getClinicRecordsInfo_strInput = "";
        java.lang.String _getClinicRecordsInfo__return = port.getClinicRecordsInfo(_getClinicRecordsInfo_strInput);
        System.out.println("getClinicRecordsInfo.result=" + _getClinicRecordsInfo__return);


        }
        {
        System.out.println("Invoking querySchedule...");
        java.lang.String _querySchedule_strInput = "";
        java.lang.String _querySchedule__return = port.querySchedule(_querySchedule_strInput);
        System.out.println("querySchedule.result=" + _querySchedule__return);


        }
        {
        System.out.println("Invoking deptInfo...");
        java.lang.String _deptInfo_strInput = "";
        java.lang.String _deptInfo__return = port.deptInfo(_deptInfo_strInput);
        System.out.println("deptInfo.result=" + _deptInfo__return);


        }
        {
        System.out.println("Invoking getPrescriptionInfo...");
        java.lang.String _getPrescriptionInfo_strInput = "";
        java.lang.String _getPrescriptionInfo__return = port.getPrescriptionInfo(_getPrescriptionInfo_strInput);
        System.out.println("getPrescriptionInfo.result=" + _getPrescriptionInfo__return);


        }
        {
        System.out.println("Invoking createProfile...");
        java.lang.String _createProfile_strInput = "";
        java.lang.String _createProfile__return = port.createProfile(_createProfile_strInput);
        System.out.println("createProfile.result=" + _createProfile__return);


        }
        {
        System.out.println("Invoking insertBooking...");
        java.lang.String _insertBooking_strInput = "";
        java.lang.String _insertBooking__return = port.insertBooking(_insertBooking_strInput);
        System.out.println("insertBooking.result=" + _insertBooking__return);


        }
        {
        System.out.println("Invoking getQueueForPatient...");
        java.lang.String _getQueueForPatient_strInput = "";
        java.lang.String _getQueueForPatient__return = port.getQueueForPatient(_getQueueForPatient_strInput);
        System.out.println("getQueueForPatient.result=" + _getQueueForPatient__return);


        }
        {
        System.out.println("Invoking getUnpaidClinicInfo...");
        java.lang.String _getUnpaidClinicInfo_strInput = "";
        java.lang.String _getUnpaidClinicInfo__return = port.getUnpaidClinicInfo(_getUnpaidClinicInfo_strInput);
        System.out.println("getUnpaidClinicInfo.result=" + _getUnpaidClinicInfo__return);


        }
        {
        System.out.println("Invoking getPatientNO...");
        java.lang.String _getPatientNO_strInput = "";
        java.lang.String _getPatientNO__return = port.getPatientNO(_getPatientNO_strInput);
        System.out.println("getPatientNO.result=" + _getPatientNO__return);


        }
        {
        System.out.println("Invoking saveFee...");
        java.lang.String _saveFee_strInput = "";
        java.lang.String _saveFee__return = port.saveFee(_saveFee_strInput);
        System.out.println("saveFee.result=" + _saveFee__return);


        }
        {
        System.out.println("Invoking getClinicState...");
        java.lang.String _getClinicState_strInput = "";
        java.lang.String _getClinicState__return = port.getClinicState(_getClinicState_strInput);
        System.out.println("getClinicState.result=" + _getClinicState__return);


        }
        {
        System.out.println("Invoking getQueueForDept...");
        java.lang.String _getQueueForDept_strInput = "";
        java.lang.String _getQueueForDept__return = port.getQueueForDept(_getQueueForDept_strInput);
        System.out.println("getQueueForDept.result=" + _getQueueForDept__return);


        }
        {
        System.out.println("Invoking getLisResultDetilInfo...");
        java.lang.String _getLisResultDetilInfo_strInput = "";
        java.lang.String _getLisResultDetilInfo__return = port.getLisResultDetilInfo(_getLisResultDetilInfo_strInput);
        System.out.println("getLisResultDetilInfo.result=" + _getLisResultDetilInfo__return);


        }

        System.exit(0);
    }

}
