# Oauth2
client:
  oauth2:
    client-id: appId # 客户端标识 ID
    secret: 123456 # 客户端安全码
    # 授权类型
    grant_types:
      - password
      - refresh_token
    # token 有效时间，单位秒
    token-validity-time: 2592000
    refresh-token-validity-time: 2592000
    # 客户端访问范围
    scopes:
      - api
      - all