# 服务网关名称
spring:
  application:
    name: gateway
  cloud:
    inetutils:
      timeout-seconds: 10  # 超时时间
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway可以发现nacos中的微服务
    nacos:
      discovery:
        server-addr: 114.55.3.21:8848
        password: nacos
        username: nacos