server:
  port: 8012  #注册中心端口号
spring:
  application:
    name: eureka-server
#  cloud:
#    inetutils:
#      timeout-seconds: 5  # 读取网卡超时时间
eureka:
  instance:
    #服务注册中心实例的主机名
    hostname: two
    prefer-ip-address: false
    # 服务刷新时间配置，每隔这个时间会主动心跳一次
    # 默认30s
    lease-renewal-interval-in-seconds: 5
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    # 注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    # 默认90s
    lease-expiration-duration-in-seconds: 15
  server:
    ####关闭自我保护机制
    enable-self-preservation: true
    # 默认180s
    # eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
    # 由于启用了evict其实就用不太上改这个配置了
    response-cache-auto-expiration-in-seconds: 60
    # 启用主动失效，并且每次主动失效检测间隔为3s
    eviction-interval-timer-in-ms: 10000
  client:
    #是否将自己注册到Eureka Server 默认为true
    fetch-registry: true
    #是否从Eureka Server查询注册信息
    register-with-eureka: true
    serviceUrl:
      #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://one:8011/eureka/

 