server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      # 这里需要注明的是 2.0之后是 JDBC-URL  2.0之前是 url
      url: jdbc:mysql://192.168.6.10:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&pinGlobalTxToPhysicalConnection=true&autoReconnect=true
      username: root
      password: 12345678
    minor: 
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://192.168.6.10:3306/test2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&pinGlobalTxToPhysicalConnection=true&autoReconnect=true
      username: root
      password: 12345678

      
com:
  dudu: 
    name: "test"
    want: "祝大家鸡年大吉吧"
    jh: ${com.dudu.name}再次${com.dudu.want}