
server:
  port: 9000
spring:
  application:
    name: feign-hystrix-consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/  #访问集群
feign:
  hystrix:
    enabled: true  #开启`断路由`
