package vip.xjdai.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2019-09-10T15:27:38.231+08:00
 * Generated source version: 3.1.17
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebserviceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebserviceSoap {

    /**
     * 获取本机注册码序号
     */
    @WebMethod(action = "http://tempuri.org/getRegCode")
    @RequestWrapper(localName = "getRegCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegCode")
    @ResponseWrapper(localName = "getRegCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegCodeResponse")
    @WebResult(name = "getRegCodeResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getRegCode();

    /**
     * 8.1 价格公示
     */
    @WebMethod(operationName = "QueryPriceBoardInfo", action = "http://tempuri.org/QueryPriceBoardInfo")
    @RequestWrapper(localName = "QueryPriceBoardInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryPriceBoardInfo")
    @ResponseWrapper(localName = "QueryPriceBoardInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryPriceBoardInfoResponse")
    @WebResult(name = "QueryPriceBoardInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String queryPriceBoardInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 7.1 住院日清单、出院清单
     */
    @WebMethod(action = "http://tempuri.org/inhosBill")
    @RequestWrapper(localName = "inhosBill", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InhosBill")
    @ResponseWrapper(localName = "inhosBillResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InhosBillResponse")
    @WebResult(name = "inhosBillResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String inhosBill(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 获取服务器时间
     */
    @WebMethod(operationName = "Getsysdate", action = "http://tempuri.org/Getsysdate")
    @RequestWrapper(localName = "Getsysdate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Getsysdate")
    @ResponseWrapper(localName = "GetsysdateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetsysdateResponse")
    @WebResult(name = "GetsysdateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getsysdate();

    /**
     * 3.1 排班信息
     */
    @WebMethod(operationName = "GetSchemaInfo", action = "http://tempuri.org/GetSchemaInfo")
    @RequestWrapper(localName = "GetSchemaInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSchemaInfo")
    @ResponseWrapper(localName = "GetSchemaInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSchemaInfoResponse")
    @WebResult(name = "GetSchemaInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getSchemaInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 10.2 门诊用药记录
     */
    @WebMethod(operationName = "GetOrderInfo", action = "http://tempuri.org/GetOrderInfo")
    @RequestWrapper(localName = "GetOrderInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderInfo")
    @ResponseWrapper(localName = "GetOrderInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderInfoResponse")
    @WebResult(name = "GetOrderInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getOrderInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 5.4 根据发票号或者收据号获取收费明细
     */
    @WebMethod(action = "http://tempuri.org/getFeeDetailByfinanceNo")
    @RequestWrapper(localName = "getFeeDetailByfinanceNo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFeeDetailByfinanceNo")
    @ResponseWrapper(localName = "getFeeDetailByfinanceNoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetFeeDetailByfinanceNoResponse")
    @WebResult(name = "getFeeDetailByfinanceNoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getFeeDetailByfinanceNo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 9.1 检验主表
     */
    @WebMethod(action = "http://tempuri.org/getLisResultInfo")
    @RequestWrapper(localName = "getLisResultInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLisResultInfo")
    @ResponseWrapper(localName = "getLisResultInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLisResultInfoResponse")
    @WebResult(name = "getLisResultInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getLisResultInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.4 通过身份证查询患者当前在院的住院编号
     */
    @WebMethod(action = "http://tempuri.org/getInpatientNo")
    @RequestWrapper(localName = "getInpatientNo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInpatientNo")
    @ResponseWrapper(localName = "getInpatientNoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInpatientNoResponse")
    @WebResult(name = "getInpatientNoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getInpatientNo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 3.3 挂号、预约转挂号
     */
    @WebMethod(action = "http://tempuri.org/insertRegisterInfo")
    @RequestWrapper(localName = "insertRegisterInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertRegisterInfo")
    @ResponseWrapper(localName = "insertRegisterInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertRegisterInfoResponse")
    @WebResult(name = "insertRegisterInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String insertRegisterInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 1.1 身份证关联的所有档案
     */
    @WebMethod(action = "http://tempuri.org/getExistProfile")
    @RequestWrapper(localName = "getExistProfile", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExistProfile")
    @ResponseWrapper(localName = "getExistProfileResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExistProfileResponse")
    @WebResult(name = "getExistProfileResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getExistProfile(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.2 医生信息
     */
    @WebMethod(operationName = "DocInfo", action = "http://tempuri.org/DocInfo")
    @RequestWrapper(localName = "DocInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DocInfo")
    @ResponseWrapper(localName = "DocInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DocInfoResponse")
    @WebResult(name = "DocInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String docInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 6.2 住院押金费充值确认
     */
    @WebMethod(action = "http://tempuri.org/hospitalizationExpensesRecharge")
    @RequestWrapper(localName = "hospitalizationExpensesRecharge", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HospitalizationExpensesRecharge")
    @ResponseWrapper(localName = "hospitalizationExpensesRechargeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HospitalizationExpensesRechargeResponse")
    @WebResult(name = "hospitalizationExpensesRechargeResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String hospitalizationExpensesRecharge(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 6.1 住院费余额查询
     */
    @WebMethod(action = "http://tempuri.org/getHospitalizationExpenses")
    @RequestWrapper(localName = "getHospitalizationExpenses", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHospitalizationExpenses")
    @ResponseWrapper(localName = "getHospitalizationExpensesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetHospitalizationExpensesResponse")
    @WebResult(name = "getHospitalizationExpensesResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getHospitalizationExpenses(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 7.2 住院日清单、出院清单
     */
    @WebMethod(action = "http://tempuri.org/inhosBillnew")
    @RequestWrapper(localName = "inhosBillnew", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InhosBillnew")
    @ResponseWrapper(localName = "inhosBillnewResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InhosBillnewResponse")
    @WebResult(name = "inhosBillnewResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String inhosBillnew(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 9.3 获取检查报告单
     */
    @WebMethod(action = "http://tempuri.org/getPacsResultInfo")
    @RequestWrapper(localName = "getPacsResultInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPacsResultInfo")
    @ResponseWrapper(localName = "getPacsResultInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPacsResultInfoResponse")
    @WebResult(name = "getPacsResultInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getPacsResultInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 3.2.1 查询预约状态
     */
    @WebMethod(action = "http://tempuri.org/getBookingState")
    @RequestWrapper(localName = "getBookingState", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookingState")
    @ResponseWrapper(localName = "getBookingStateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetBookingStateResponse")
    @WebResult(name = "getBookingStateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getBookingState(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 10.1 查询历次门诊就诊记录
     */
    @WebMethod(action = "http://tempuri.org/getClinicRecordsInfo")
    @RequestWrapper(localName = "getClinicRecordsInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClinicRecordsInfo")
    @ResponseWrapper(localName = "getClinicRecordsInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClinicRecordsInfoResponse")
    @WebResult(name = "getClinicRecordsInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getClinicRecordsInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.1获取医生排班
     */
    @WebMethod(action = "http://tempuri.org/querySchedule")
    @RequestWrapper(localName = "querySchedule", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuerySchedule")
    @ResponseWrapper(localName = "queryScheduleResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QueryScheduleResponse")
    @WebResult(name = "queryScheduleResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String querySchedule(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.1 科室信息
     */
    @WebMethod(operationName = "DeptInfo", action = "http://tempuri.org/DeptInfo")
    @RequestWrapper(localName = "DeptInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeptInfo")
    @ResponseWrapper(localName = "DeptInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeptInfoResponse")
    @WebResult(name = "DeptInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String deptInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 5.2 获取处方信息
     */
    @WebMethod(action = "http://tempuri.org/getPrescriptionInfo")
    @RequestWrapper(localName = "getPrescriptionInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPrescriptionInfo")
    @ResponseWrapper(localName = "getPrescriptionInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPrescriptionInfoResponse")
    @WebResult(name = "getPrescriptionInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getPrescriptionInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 1.2 建立门诊档案
     */
    @WebMethod(operationName = "CreateProfile", action = "http://tempuri.org/CreateProfile")
    @RequestWrapper(localName = "CreateProfile", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateProfile")
    @ResponseWrapper(localName = "CreateProfileResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateProfileResponse")
    @WebResult(name = "CreateProfileResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String createProfile(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 3.2 预约挂号、预约取消
     */
    @WebMethod(action = "http://tempuri.org/insertBooking")
    @RequestWrapper(localName = "insertBooking", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertBooking")
    @ResponseWrapper(localName = "insertBookingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertBookingResponse")
    @WebResult(name = "insertBookingResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String insertBooking(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 4.2患者排队查询
     */
    @WebMethod(action = "http://tempuri.org/getQueueForPatient")
    @RequestWrapper(localName = "getQueueForPatient", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQueueForPatient")
    @ResponseWrapper(localName = "getQueueForPatientResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQueueForPatientResponse")
    @WebResult(name = "getQueueForPatientResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getQueueForPatient(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 5.1 获取有未缴费处方的门诊记录
     */
    @WebMethod(action = "http://tempuri.org/getUnpaidClinicInfo")
    @RequestWrapper(localName = "getUnpaidClinicInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnpaidClinicInfo")
    @ResponseWrapper(localName = "getUnpaidClinicInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnpaidClinicInfoResponse")
    @WebResult(name = "getUnpaidClinicInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getUnpaidClinicInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 2.3 通过实物就诊卡查询患者在医院的门诊患者编号
     */
    @WebMethod(action = "http://tempuri.org/getPatientNO")
    @RequestWrapper(localName = "getPatientNO", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPatientNO")
    @ResponseWrapper(localName = "getPatientNOResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPatientNOResponse")
    @WebResult(name = "getPatientNOResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getPatientNO(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 5.3 门诊结算确认
     */
    @WebMethod(action = "http://tempuri.org/saveFee")
    @RequestWrapper(localName = "saveFee", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveFee")
    @ResponseWrapper(localName = "saveFeeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveFeeResponse")
    @WebResult(name = "saveFeeResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String saveFee(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 3.4 查询挂号状态
     */
    @WebMethod(action = "http://tempuri.org/getClinicState")
    @RequestWrapper(localName = "getClinicState", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClinicState")
    @ResponseWrapper(localName = "getClinicStateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClinicStateResponse")
    @WebResult(name = "getClinicStateResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getClinicState(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 4.1科室排队查询
     */
    @WebMethod(action = "http://tempuri.org/getQueueForDept")
    @RequestWrapper(localName = "getQueueForDept", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQueueForDept")
    @ResponseWrapper(localName = "getQueueForDeptResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetQueueForDeptResponse")
    @WebResult(name = "getQueueForDeptResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getQueueForDept(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );

    /**
     * 9.2 检验明细
     */
    @WebMethod(action = "http://tempuri.org/getLisResultDetilInfo")
    @RequestWrapper(localName = "getLisResultDetilInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLisResultDetilInfo")
    @ResponseWrapper(localName = "getLisResultDetilInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLisResultDetilInfoResponse")
    @WebResult(name = "getLisResultDetilInfoResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String getLisResultDetilInfo(
        @WebParam(name = "strInput", targetNamespace = "http://tempuri.org/")
        java.lang.String strInput
    );
}
