server:
  port: 1111
spring:
  application:
    name: eureka-server
eureka:
  instance:
    appname: peer1  
  client:
    service-url:
      defaultZone: http://peer2:1112/eureka/,http://peer3:1113/eureka/